import 'package:dartz/dartz.dart';
import '../../../../core/error/failures.dart';
import '../../../../core/usecases/base_usecase.dart';
import '../entities/sales_order_entity.dart';
import '../repositories/order_repository.dart';

/// Use case for creating a new sales order with its line items.
///
/// Validates that the order has at least one item before delegating
/// to the repository. The order number should be pre-generated by the
/// caller using the NumberingConfig system.
class CreateSalesOrderUseCase
    extends UseCase<SalesOrder, CreateSalesOrderParams> {
  final OrderRepository repository;

  CreateSalesOrderUseCase(this.repository);

  @override
  Future<Either<Failure, SalesOrder>> call(CreateSalesOrderParams params) async {
    if (params.order.items.isEmpty) {
      return const Left(
        ValidationFailure(message: 'Order must have at least one item'),
      );
    }
    if (params.order.totalAmount < 0) {
      return const Left(
        ValidationFailure(message: 'Order total cannot be negative'),
      );
    }
    return await repository.createSalesOrder(params.order);
  }
}

/// Parameters for the [CreateSalesOrderUseCase].
class CreateSalesOrderParams {
  /// The sales order to create.
  final SalesOrder order;

  const CreateSalesOrderParams({required this.order});
}
