import 'package:dartz/dartz.dart';
import '../../../../core/error/failures.dart';
import '../../../../core/usecases/base_usecase.dart';
import '../entities/purchase_order_entity.dart';
import '../repositories/order_repository.dart';

/// Use case for creating a new purchase order with its line items.
///
/// Validates that the order has at least one item before delegating
/// to the repository. The order number should be pre-generated by the
/// caller using the NumberingConfig system.
class CreatePurchaseOrderUseCase
    extends UseCase<PurchaseOrder, CreatePurchaseOrderParams> {
  final OrderRepository repository;

  CreatePurchaseOrderUseCase(this.repository);

  @override
  Future<Either<Failure, PurchaseOrder>> call(
    CreatePurchaseOrderParams params,
  ) async {
    if (params.order.items.isEmpty) {
      return const Left(
        ValidationFailure(message: 'Order must have at least one item'),
      );
    }
    if (params.order.totalAmount < 0) {
      return const Left(
        ValidationFailure(message: 'Order total cannot be negative'),
      );
    }
    return await repository.createPurchaseOrder(params.order);
  }
}

/// Parameters for the [CreatePurchaseOrderUseCase].
class CreatePurchaseOrderParams {
  /// The purchase order to create.
  final PurchaseOrder order;

  const CreatePurchaseOrderParams({required this.order});
}
