import 'package:equatable/equatable.dart';
import 'package:dartz/dartz.dart';
import '../../../../core/error/failures.dart';
import '../entities/dashboard_entity.dart';

/// Abstract repository contract for dashboard data aggregation operations.
///
/// This interface defines the data access boundary for the dashboard feature.
/// The dashboard is a read-only summary screen that aggregates data from
/// multiple features (sales, inventory, customers, loyalty, purchases,
/// employees, sync) into a single view.
///
/// All methods return [Either<Failure, T>] to enable functional error handling
/// without exceptions, following the Clean Architecture data flow convention.
abstract class DashboardRepository {
  /// Aggregates all dashboard statistics from local data sources.
  /// Combines sales, inventory, customer, loyalty, purchase, employee,
  /// and sync metrics into a single [DashboardStats] snapshot.
  Future<Either<Failure, DashboardStats>> getDashboardStats();

  /// Retrieves the most recent sales for the dashboard widget.
  /// [limit] controls the number of recent sales returned (default: 10).
  Future<Either<Failure, List<RecentSale>>> getRecentSales({int limit = 10});

  /// Retrieves the top-selling products by revenue for the dashboard.
  /// [limit] controls the number of top products returned (default: 5).
  Future<Either<Failure, List<TopProduct>>> getTopProducts({int limit = 5});

  /// Retrieves active alerts requiring attention (low stock, sync failures, etc.).
  Future<Either<Failure, List<AlertItem>>> getAlerts();
}

/// Lightweight representation of a recent sale for the dashboard widget.
class RecentSale extends Equatable {
  /// Unique identifier for the bill (UUID format).
  final String id;

  /// Human-readable bill number (e.g., "BILL-000123").
  final String billNumber;

  /// Customer name if linked, or "Walk-in" for anonymous sales.
  final String? customerName;

  /// Total bill amount in paise.
  final int amount;

  /// Timestamp when the sale was completed.
  final DateTime createdAt;

  const RecentSale({
    required this.id,
    required this.billNumber,
    this.customerName,
    required this.amount,
    required this.createdAt,
  });

  @override
  List<Object?> get props => [id, billNumber, customerName, amount, createdAt];
}

/// Lightweight representation of a top-selling product for the dashboard.
class TopProduct extends Equatable {
  /// Foreign key to the [Product] entity.
  final String productId;

  /// Product name for display in the top-products list.
  final String productName;

  /// Total quantity sold in the current period (e.g., today or this month).
  final int quantitySold;

  /// Total revenue generated by this product in paise.
  final int revenue;

  const TopProduct({
    required this.productId,
    required this.productName,
    required this.quantitySold,
    required this.revenue,
  });

  @override
  List<Object?> get props => [productId, productName, quantitySold, revenue];
}

/// Dashboard alert item requiring user attention or action.
class AlertItem extends Equatable {
  /// Unique identifier for this alert (UUID format).
  final String id;

  /// Alert category: 'low_stock', 'sync_failed', 'expiry_warning', 'credit_limit', etc.
  final String type;

  /// Short alert title for display in the notification bar.
  final String title;

  /// Detailed alert message explaining the issue and suggested action.
  final String message;

  /// Timestamp when the alert was generated.
  final DateTime createdAt;

  const AlertItem({
    required this.id,
    required this.type,
    required this.title,
    required this.message,
    required this.createdAt,
  });

  @override
  List<Object?> get props => [id, type, title, message, createdAt];
}
